Centos6
niclabs/docker pull request #24
Opened 2016-11-17 16:02 UTC by raticate

file integrity checks added

2016-11-17 16:22 UTC, fmontoto commented
Remove the compiler at the end of the Dockerfile and other installation only dependencies.

2016-11-17 17:31 UTC, fmontoto requested changes

2016-11-17 17:31 UTC, fmontoto commented on tchsm/lib/centos6/Dockerfile
> +# && git checkout a9a3e299a46 \
Add the checkout to v0.1
EDIT:
Actually, download the zip of the release (https://github.com/niclabs/tchsm-libdtc/archive/v0.1.zip) and do a hash check.
We should also have the same with libtc, can you do a release of it?

2016-11-17 17:31 UTC, fmontoto commented on tchsm/lib/centos6/Dockerfile
> + && cd /tmp/libconfig-1.5 && ./configure && make install \
Add a hash check here

2016-11-17 17:31 UTC, fmontoto commented on tchsm/lib/centos6/Dockerfile
> +
&& cd / && rm -r /tmp/zeromq-4.1.4 \
&& rm -r /tmp/zeromq-4.1.4

2016-11-18 20:02 UTC, raticate commented on tchsm/lib/centos6/Dockerfile
> +
??

2016-11-24 15:21 UTC, raticate commented on tchsm/lib/centos6/Dockerfile
> +
I really don't get this

2016-11-24 15:43 UTC, fmontoto approved these changes

2016-11-24 15:44 UTC, merged